### PR TITLE
Added support for speakeasy options

### PR DESCRIPTION
**Pull request by rodmoreno**
I create a refactor to support another speakeasy options on methods that support it:

- `generateToken`
- `generateAuthURL`
- `generateQRCode`
- `verify`

Also I added a new option for the plugin: `totpStep` to define a default step time.

### CODE REVIEW

**Comment by zuck** [comment]
Hello @rodmoreno !  Thank you for this PR!

In order to merge it, you should first:
- backport to `fastify 2.x`
- commit the `package-lock.json` too

**Comment by rodmoreno** [comment]
Not problem @zuck! I've already submitted two new commits with changes required

**Comment by rodmoreno** [comment]
Hey @zuck days ago I sent a couple of commits with your recommendations, I don't know if you have had opportunity to review them and if you have any additional comment/suggestion. Thanks

**Comment by zuck** [comment]
Hi @rodmoreno , thanks for your contribution! A new version, with this change, will be released ASAP!

**Pull request merged**
